---
 - hosts: database
   become: true
   tasks:
    - name: install tools
      apt: name={{item}} state=present update_cache=yes
      with_items:
       - mysql-server
       - python-mysqldb

    - name: ensure mysql-server started
      service: name=mysql state=started enabled=yes
      notify: restart mysql server

    - name: ensure mysql listing on all ports 
      lineinfile: dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp=^bind-address line="bind-address = 0.0.0.0"
      notify: restart mysql server

    - name: create demo database
      mysql_db: name=demo state=present

    - name: create demo user
      mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=present

   handlers:
    - name: restart mysql server
      service: name=mysql state=restarted enabled=yes
    
